feat: Add 4.9.0 to Catalog for Main and Spring Boot
KaotoIO/kaoto pull request #1691
Opened 2024-12-04 13:09 UTC by apupier

wondering if we should wait for Camel Kamelet and Camel Quarkus aligned with that too.

2024-12-04 13:21 UTC, apupier commented
a bunch of tests to adjust (and to verify it is right to adjust and not a regression):

```
[@kaoto/kaoto]: Tests:       9 failed, 1 skipped, 2 todo, 1325 passed, 1337 total
[@kaoto/kaoto]: Snapshots:   7 failed, 134 passed, 141 total
```

2024-12-04 13:22 UTC, oscerd commented
Camel Kamelets 4.9.0 is on vote.

2024-12-04 14:45 UTC, lordrip commented
There are snapshots broken due to new parameters in some EIPs and the dataformat test is broken probably due to a new one being included.

2024-12-05 13:53 UTC, lordrip approved these changes

2024-12-06 09:11 UTC, lhein commented on packages/catalog-generator/scripts/build-catalogs.mjs
> +  SpringBoot: ['4.9.0', '4.4.4', '4.4.0.redhat-00039', '4.8.0.redhat-00022'],
4.8.1 as LTS should stay and only be upgraded to 4.8.2. That also applies to Main

2024-12-06 09:14 UTC, lhein requested changes
see my comment

2024-12-06 11:07 UTC, lhein approved these changes

2024-12-08 18:01 UTC, lhein commented
Quarkus version still to be changed.

2024-12-09 09:23 UTC, merged